name: Build 👉 Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Setup release
        uses: softprops/action-gh-release@v1
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-folder
          path: |
            dist
